[package]
name = "mapreduce"
version = "0.1.0"
edition = "2024"

[dependencies]
rquickjs =  { version = "0.9.0", features = ["parallel"] }
log = "0.4.17"
clap = { version = "4.0.4", features = ["derive", "cargo"]}
env_logger = "0.11.8"
anyhow = "1.0"
thiserror = "2.0.12"